<template>
	<svg
		width="0"
		height="0"
		style="position: absolute"
	>
		<defs>
			<marker
				id="marker-arrow-end"
				markerWidth="8"
				markerHeight="8"
				refX="9"
				refY="3"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<path
					d="M0,0 L0,6 L9,3 z"
					fill="context-stroke"
				/>
			</marker>
			<marker
				id="marker-arrow-start"
				markerWidth="8"
				markerHeight="8"
				refX="0"
				refY="3"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<path
					d="M9,0 L9,6 L0,3 z"
					fill="context-stroke"
				/>
			</marker>
			<marker
				id="marker-circle-end"
				markerWidth="6"
				markerHeight="6"
				refX="3"
				refY="3"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<circle
					sx="3"
					sy="3"
					r="2.5"
					fill="context-stroke"
				/>
			</marker>
			<marker
				id="marker-circle-start"
				markerWidth="6"
				markerHeight="6"
				refX="3"
				refY="3"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<circle
					sx="3"
					sy="3"
					r="2.5"
					fill="context-stroke"
				/>
			</marker>
			<marker
				id="marker-diamond-end"
				markerWidth="8"
				markerHeight="8"
				refX="4"
				refY="4"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<path
					d="M0,4 L4,8 L8,4 L4,0 z"
					fill="context-stroke"
				/>
			</marker>
			<marker
				id="marker-diamond-start"
				markerWidth="8"
				markerHeight="8"
				refX="4"
				refY="4"
				orient="auto"
				markerUnits="strokeWidth"
			>
				<path
					d="M0,4 L4,8 L8,4 L4,0 z"
					fill="context-stroke"
				/>
			</marker>
		</defs>
	</svg>
</template>
